import type { Report, Finding } from "../types.js";
import { formatUsd } from "../pricing.js";

function fmt(n: number): string {
  return n.toLocaleString();
}

function severityEmoji(s: Finding["severity"]): string {
  if (s === "high") return "🔴";
  if (s === "warn") return "🟡";
  return "🔵";
}

export function renderMarkdown(report: Report): string {
  const { session, findings, wasteScore, wastedCostUsd } = report;
  const totals = session.totals;
  const lines: string[] = [];

  lines.push(`# 💀 Prompt Graveyard — Session Report`);
  lines.push("");
  lines.push(`**Session:** \`${session.sessionId}\`  `);
  lines.push(`**Project:** \`${session.cwd}\`  `);
  if (session.gitBranch) lines.push(`**Branch:** \`${session.gitBranch}\`  `);
  if (session.models.length > 0) lines.push(`**Models:** ${session.models.join(", ")}  `);
  lines.push(`**Turns:** ${session.turns.length}  `);
  lines.push(`**Started:** ${session.startedAt}  `);
  lines.push("");

  lines.push(`## Token breakdown`);
  lines.push("");
  lines.push(`| Token type | Count |`);
  lines.push(`| --- | ---: |`);
  lines.push(`| Input (uncached) | ${fmt(totals.inputTokens)} |`);
  lines.push(`| Cache creation | ${fmt(totals.cacheCreationTokens)} |`);
  lines.push(`| Cache read | ${fmt(totals.cacheReadTokens)} |`);
  lines.push(`| Output | ${fmt(totals.outputTokens)} |`);
  lines.push(`| **Total** | **${fmt(totals.grandTotal)}** |`);
  lines.push("");

  lines.push(`## Headline`);
  lines.push("");
  lines.push(`- **API-equivalent cost:** ${formatUsd(totals.costUsd)} _(public pay-as-you-go rates; Pro/Max subs absorb this)_`);
  lines.push(`- **Waste score:** \`${wasteScore}/100\``);
  lines.push(`- **Estimated wasted spend:** ~${formatUsd(wastedCostUsd)}`);
  lines.push("");

  if (findings.length === 0) {
    lines.push(`## Findings`);
    lines.push("");
    lines.push(`No waste patterns detected. 🎉`);
    return lines.join("\n");
  }

  lines.push(`## Findings (${findings.length})`);
  lines.push("");

  const grouped = new Map<string, Finding[]>();
  for (const f of findings) {
    const arr = grouped.get(f.detector) ?? [];
    arr.push(f);
    grouped.set(f.detector, arr);
  }

  for (const [detector, items] of grouped) {
    lines.push(`### \`${detector}\` (${items.length})`);
    lines.push("");
    for (const f of items) {
      lines.push(`- ${severityEmoji(f.severity)} **${f.title}**`);
      lines.push(`  - ${f.detail}`);
      if (f.wastedTokens) {
        lines.push(`  - _~${fmt(f.wastedTokens)} tokens implicated_`);
      }
      lines.push(`  - turns: ${f.turnIndices.map((i) => `\`${i}\``).join(", ")}`);
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by [prompt-graveyard](https://github.com/Aleezah1429/prompt-graveyard)_`);
  return lines.join("\n");
}
